version: '3'
services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    networks:
      - coopido-network

  frontend:
    container_name: web
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - coopido-network
    depends_on:
      - backend

networks:
  coopido-network:
    driver: overlay
    attachable: true