version: '3'
services:
  web:
    container_name: web
    build:
      context: ./boilerplate
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
      - '49153:49153'
    networks:
      - boilerplate-network
    volumes:
      - ./boilerplate:/usr/app

networks:
  boilerplate-network:
    driver: overlay
    attachable: true

volumes:
  frontend:
